//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by StkUI.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_SIMTYPE                     129
#define IDD_SETGROUP                    130
#define IDR_MAINBAR                     131
#define IDR_PERIODBAR                   132
#define IDI_INDICATOR                   133
#define IDR_CURVEBAR                    134
#define IDR_SLISTBAR                    136
#define IDD_WIZARD_FORM                 137
#define IDR_VIEWBAR                     138
#define IDR_SIMUBAR                     139
#define IDD_PROGRESS                    140
#define IDR_MENUTOOLBAR                 142
#define IDB_COLORMENU                   144
#define IDB_WORKSP_TAB                  145
#define IDB_WORKSP_BOX                  146
#define IDB_SPLASH                      147
#define IDB_HELPLOGO                    148
#define IDB_STRATEGYVIEW_ICONS          149
#define IDB_MENUCHECKED                 150
#define IDR_MENU_MAINBARSETTING         151
#define IDR_MENU_MAINBARVIEW            152
#define IDR_MENU_MAINBARTECH            153
#define IDR_MENU_MAINBARPERIOD          154
#define IDR_POPUP_SLIST                 155
#define IDR_POPUP_SLISTVIEW             156
#define IDR_POPUP_GRAPH                 157
#define IDR_POPUP_GRAPHVIEW             158
#define IDR_MENU_VIEWBARLINETYPE        159
#define IDR_MENU_VIEWBARMULTI           160
#define IDD_SETPRPT                     161
#define IDD_CLOSESTRATEGYDLG            163
#define IDB_STRATEGY                    164
#define IDD_DOWNLOAD                    165
#define IDD_PROXYSET                    166
#define IDD_INSTALLPACKAGE              167
#define IDB_PACKAGE                     168
#define IDD_DATASOURCE                  169
#define IDB_DLGLEFTLOGO                 171
#define IDR_TEXT_DECLARE                172
#define IDB_DLGTOPLOGO                  174
#define IDB_STARTLOGO                   175
#define IDR_MENU_SLISTBARCLASS          176
#define IDB_WIZARDHEADER                177
#define IDD_SETCOLUMN                   178
#define IDR_MENU_SLISTBARGROUP          179
#define IDD_BASEINDEX                   180
#define IDR_MENU_SLISTBARDOMAIN         181
#define IDD_AUTOUPGRADE                 182
#define IDR_TEXT_UPGRADEEXPLAIN         183
#define IDD_LISTEXPORT                  184
#define IDI_BALANG                      185
#define IDD_SELECTGRP                   186
#define IDD_SELECTSTK                   187
#define IDD_EXPORTDEST                  188
#define IDD_EXPORTOPTION                189
#define IDD_SETDRDATA                   190
#define IDB_BALANG                      191
#define IDD_NETINFO                     192
#define IDB_GROUPVIEW_ICONS             193
#define IDD_SETPARAM                    195
#define IDB_TECHSVIEW_ICONS             196
#define IDI_OK                          197
#define IDDP_MA                         198
#define IDI_CANCEL                      199
#define IDDP_BBI                        200
#define IDR_SIMTYPE2                    201
#define IDDP_BOLL                       202
#define IDB_STRATEGYLARGE               203
#define IDDP_PV                         204
#define IDDP_SAR                        205
#define IDR_POPUP_WIZARDVIEWLISTTYPE    206
#define IDDP_DJ                         207
#define IDDP_CW                         208
#define IDD_SIMU_FORM                   209
#define IDD_STRATEGYREPORT              210
#define IDD_EDITKDATA                   211
#define IDR_POPUP_WIZARDVIEW            212
#define IDD_SETRATE                     213
#define IDR_POPUP_SIMUVIEW              214
#define IDD_SETRULE                     215
#define IDR_POPUP_BASEVIEW              216
#define IDD_SIMUREPORT                  217
#define IDR_POPUP_SETTING               218
#define IDD_SIMUREALOP                  219
#define IDR_POPUP_REALTIMEVIEW          219
#define IDD_SETCOLOR                    220
#define IDR_POPUP_MULTISORTVIEW         220
#define IDI_STRATEGY                    221
#define IDI_STRATEGY2                   223
#define IDB_STRATEGYKING                225
#define IDD_SIMUSTAT                    226
#define IDD_SIMUADDOP                   227
#define IDB_WORKSPBAR_BTN               228
#define IDD_SIMUADDSTOCK                229
#define IDD_FILTERINFO                  230
#define IDDP_MACD                       235
#define IDDP_MIKE                       236
#define IDDP_PSY                        237
#define IDDP_VOLUME                     238
#define IDDP_NVI                        239
#define IDDP_PVI                        240
#define IDDP_VR                         241
#define IDDP_VROC                       242
#define IDDP_OBV                        243
#define IDDP_MOBV                       244
#define IDDP_MFI                        245
#define IDDP_VMACD                      246
#define IDDP_WVAD                       247
#define IDDP_EMV                        248
#define IDDP_VRSI                       249
#define IDDP_NVRSI                      250
#define IDDP_AD                         251
#define IDDP_CI                         252
#define IDDP_KDJ                        253
#define IDDP_R                          254
#define IDDP_RSI                        255
#define IDDP_BIAS                       256
#define IDDP_MTM                        257
#define IDDP_DMI                        258
#define IDDP_ROC                        259
#define IDDP_CCI                        260
#define IDDP_CV                         261
#define IDDP_ARBR                       262
#define IDDP_CR                         263
#define IDDP_OSC                        264
#define IDDP_UOS                        265
#define IDDP_MAOSC                      266
#define IDDP_36BIAS                     267
#define IDDP_DPO                        268
#define IDDP_KST                        269
#define IDDP_REI                        270
#define IDDP_DMKI                       271
#define IDDP_PCNT                       272
#define IDDP_HLC                        273
#define IDDP_CDP                        274
#define IDDP_ASI                        275
#define IDDP_ATR                        276
#define IDD_SIMUADVANCED                278
#define IDDP_CYO                        279
#define IDDP_DCYO                       280
#define IDDP_HSL                        281
#define IDDP_DPER                       282
#define IDD_TYDATA                      283
#define IDD_SELECTTRADER                284
#define IDD_INSTALLFXJ                  285
#define IDI_ZLINKER                     285
#define IDD_SETBASE                     286
#define IDI_ALARM_INDEXGREEN            287
#define IDD_SETBASEDATA                 288
#define IDI_ALARM_WARNING               288
#define IDD_SETKDATA                    289
#define IDI_ALARM_INDEXRED              289
#define IDD_CACHELOAD                   290
#define IDD_ALARMSETTING                295
#define IDD_ALARMRESULT                 296
#define IDD_SELECTOR_FORM               298
#define IDC_URL_ADDRESS                 1000
#define IDC_PROGRESS                    1001
#define IDC_EDITCODE                    1001
#define IDC_MESSAGE                     1002
#define IDC_COMBO_GROUPSRC              1002
#define IDC_LIST_STOCKSRC               1003
#define IDC_CODEJOCKEY                  1004
#define IDC_ADDSELECTED                 1004
#define IDC_EDITA                       1004
#define IDC_ADDALL                      1005
#define IDC_EDITB                       1005
#define IDC_URL_MAILME                  1006
#define IDC_REMOVESELECTED              1006
#define IDC_EDITH                       1006
#define IDC_USER                        1007
#define IDC_REMOVEALL                   1007
#define IDC_EDITNATIONAL                1007
#define IDC_REGCODE                     1008
#define IDC_LIST_STOCKDEST              1008
#define IDC_EDITCORP                    1008
#define IDC_COMBO_GROUPDEST             1009
#define IDC_EDITTOTAL                   1009
#define IDC_TITLE                       1010
#define IDC_EDIT_NEWGNAME               1010
#define IDC_STRATEGYLIST                1011
#define IDC_ADDGROUP                    1011
#define IDC_DESCRIPT                    1011
#define IDC_FILENAME                    1012
#define IDC_DELETEGROUP                 1012
#define IDC_EXPLORE                     1013
#define IDC_CLOSEALL                    1014
#define IDC_CHECK_BASE                  1015
#define IDC_CHECK_DAY                   1016
#define IDC_CHECK_XDR                   1017
#define IDC_COMBO_SERVERS               1018
#define IDC_REFRESH_SERVERS             1019
#define IDC_STOP                        1020
#define IDC_STATIC_REFRESH              1021
#define IDC_STOP_REFRESH                1022
#define IDC_PROXY_SET                   1023
#define IDC_TIME_DAYFROM                1031
#define IDC_TIME_DAYTO                  1032
#define IDC_DL_PROGRESS                 1034
#define IDC_STATIC_STATUS               1035
#define IDC_EDIT_PROXY                  1037
#define IDC_STATIC_PROXYPORT            1038
#define IDC_EDIT_PROXYPORT              1039
#define IDC_STATIC_PROXY                1040
#define IDC_DIRECT                      1041
#define IDC_PRECONFIG                   1042
#define IDC_PROXY                       1043
#define IDC_CHECK_CODETBL               1044
#define IDC_EXPLORER                    1046
#define IDC_STATIC_PRO                  1047
#define IDC_DAYPACKAGE                  1051
#define IDC_MIN5PACKAGE                 1052
#define IDC_GODOWNLOADWEB               1054
#define IDC_CHECK_MIN5                  1055
#define IDC_TIME_MIN5FROM               1056
#define IDC_TIME_MIN5TO                 1057
#define IDC_LIST_FILES                  1058
#define IDC_REMOVE                      1062
#define IDC_ADDTOGROUP                  1064
#define IDC_STATIC_PROGRESS             1065
#define IDC_CHECK_QIANLONG              1066
#define IDC_EDIT_QLPATH                 1067
#define IDC_QLEXPLORER                  1069
#define IDC_QLTEST                      1070
#define IDC_PICTURE                     1076
#define IDC_USERNAME                    1078
#define IDC_SOFTNO                      1079
#define IDC_EMAIL                       1079
#define IDC_GOPURCHASE                  1081
#define IDC_DISPACHTITLE                1082
#define IDC_DISPATCHUSER                1083
#define IDC_EDIT_NSA                    1087
#define IDC_LEFTDAYS                    1088
#define IDC_LEFTDAYSTITLE               1089
#define IDC_BTNNEWSTRATEGY              1093
#define IDC_BTNOPENSTRATEGY             1094
#define IDC_BTNHELP                     1095
#define IDC_MOVEUP                      1096
#define IDC_MOVEDOWN                    1097
#define IDC_COLUMNLIST                  1098
#define IDC_NEWINDEX                    1099
#define IDC_EDITINDEX                   1100
#define IDC_LISTTYPE                    1100
#define IDC_DELINDEX                    1101
#define IDC_INDEXNAME                   1102
#define IDC_SETDEFAULT                  1102
#define IDC_SETALL                      1103
#define IDC_INDEXEXPRESS                1104
#define IDC_ADDTOLIST                   1109
#define IDC_STATIC_LATEST               1112
#define IDC_EDIT_EXPLAIN                1118
#define IDC_ITEM_ALL                    1120
#define IDC_ITEM_SELECTED               1121
#define IDC_ITEM_DEFINE                 1122
#define IDC_ITEM_BEGIN                  1123
#define IDC_ITEM_END                    1124
#define IDC_TXT_CHECK                   1125
#define IDC_TXT_DEST                    1126
#define IDC_TXT_EXPLORER                1127
#define IDC_EXPORT_OVERWRITE            1128
#define IDC_EXPORT_APPEND               1129
#define IDC_MDB_CHECK                   1130
#define IDC_MDB_DEST                    1131
#define IDC_MDB_EXPLORER                1132
#define IDC_CSV_CHECK                   1133
#define IDC_CSV_DEST                    1134
#define IDC_CSV_EXPLORER                1135
#define IDC_EXEONFINISH                 1136
#define IDC_ODBC_DEST                   1137
#define IDC_BUTTON1                     1139
#define IDC_HOWTO_REG                   1139
#define IDC_ODBC_SOURCE                 1139
#define IDC_INSERT                      1139
#define IDC_DEFAULT                     1139
#define IDC_WORKSPBK                    1139
#define IDC_COPY                        1139
#define IDC_RULELONG                    1139
#define IDC_ADVANCED                    1139
#define IDC_STATIC_REGISTER             1140
#define IDC_WORKSPTEXT                  1140
#define IDC_STATYIELD                   1140
#define IDC_RULEINDEX                   1140
#define IDC_IMPORT                      1140
#define IDC_GOTO_REALTIME               1140
#define IDC_BORDER                      1141
#define IDC_COPY_SOFTNO                 1141
#define IDC_IMPORTFXJ                   1141
#define IDC_GOTO_GRAPH                  1141
#define IDC_STATIC_SOFTNOTITLE          1142
#define IDC_RISE                        1142
#define IDC_APPLYFOR_EVA                1142
#define IDC_GOTO_BASE                   1143
#define IDC_ODBC_CHECK                  1144
#define IDC_SIMUBK                      1144
#define IDC_STATIC_INFO                 1145
#define IDC_SLISTBK                     1145
#define IDC_LISTGROUP                   1146
#define IDC_SLISTSELECTED               1146
#define IDC_TIME_ALL                    1147
#define IDC_BASEBK                      1147
#define IDC_TIME_DEFINE                 1148
#define IDC_BASETEXT                    1148
#define IDC_TIME_BEGIN                  1149
#define IDC_GRAPHBK                     1149
#define IDC_TIME_END                    1150
#define IDC_FALL                        1150
#define IDC_KMONTH                      1151
#define IDC_FALLENTITY                  1151
#define IDC_KWEEK                       1152
#define IDC_PLANE                       1152
#define IDC_KDAY                        1153
#define IDC_NEWKLINE                    1153
#define IDC_KMIN60                      1154
#define IDC_CW                          1154
#define IDC_KMIN30                      1155
#define IDC_TEXT                        1155
#define IDC_KMIN15                      1156
#define IDC_LINE1                       1156
#define IDC_KMIN5                       1157
#define IDC_LINE2                       1157
#define IDC_TIME_AUTORESUMEDRBEGIN      1158
#define IDC_LINE3                       1158
#define IDC_NORESUMEDR                  1159
#define IDC_LINE4                       1159
#define IDC_RESUMEDRUP                  1160
#define IDC_LINE5                       1160
#define IDC_RESUMEDRDOWN                1161
#define IDC_SIMUTEXT                    1161
#define IDC_AUTORESUMEDR                1162
#define IDC_AUTORESUMEDR_LIMIT          1163
#define IDC_DELETE                      1165
#define IDC_GRID                        1166
#define IDC_ADD                         1166
#define IDC_ADDOP                       1166
#define IDC_STATICSTOCK                 1167
#define IDC_DELETESTOCK                 1167
#define IDC_ADDSTOCK                    1168
#define IDC_MODIFY                      1168
#define IDC_TIME_DRDATA                 1169
#define IDC_MODIFIED                    1169
#define IDC_VERSION                     1170
#define IDC_RESETALL                    1170
#define IDC_NOTSHOWLATER                1172
#define IDC_NETINFOURL                  1173
#define IDC_LIST                        1174
#define IDC_ALLDEFAULT                  1175
#define IDC_STATIC_NAME                 1178
#define IDC_STDMA                       1179
#define IDC_EXPMA                       1180
#define IDC_MA1                         1181
#define IDC_DAYS1                       1182
#define IDC_MA2                         1183
#define IDC_DAYS2                       1184
#define IDC_MA3                         1185
#define IDC_DAYS3                       1186
#define IDC_MA4                         1187
#define IDC_DAYS4                       1188
#define IDC_MA5                         1189
#define IDC_DAYS5                       1190
#define IDC_MA6                         1191
#define IDC_DAYS6                       1192
#define IDC_PARAMHELP                   1193
#define IDC_DAYS                        1195
#define IDC_MULTIUP                     1196
#define IDC_AFSTEP                      1196
#define IDC_MADAYSA                     1196
#define IDC_DIFFPERCENTLESS             1196
#define IDC_MULTIDOWN                   1197
#define IDC_AFMAX                       1197
#define IDC_MADAYSB                     1197
#define IDC_TRADEVOLUME                 1197
#define IDC_RADIOMIN                    1198
#define IDC_MADAYSC                     1198
#define IDC_RADIOMAX                    1199
#define IDC_CHANGEHAND                  1199
#define IDC_MADAYSD                     1199
#define IDC_DJSHA                       1200
#define IDC_DJSZN                       1201
#define IDC_TREE                        1201
#define IDC_STOREDIV                    1203
#define IDC_COMBO_KTYPE                 1204
#define IDC_KTYPE                       1204
#define IDC_START                       1205
#define IDC_TECH                        1205
#define IDC_MAINDATATYPE                1206
#define IDC_BEST                        1206
#define IDC_REPORT                      1207
#define IDC_REPORTLIST                  1207
#define IDC_LONGTERM                    1207
#define IDC_SELECTSTK                   1208
#define IDC_NEXTDATE                    1208
#define IDC_SHORTTERM                   1208
#define IDC_SETRATE                     1209
#define IDC_SETRULE                     1210
#define IDC_REALOP                      1211
#define IDC_YIELD                       1212
#define IDC_STATICYIELD                 1212
#define IDC_TAXSZNA                     1213
#define IDC_SETPRPT                     1213
#define IDC_TAXSZNB                     1214
#define IDC_DATE                        1214
#define IDC_BUYLIMIT                    1214
#define IDC_TAXSZNFUND                  1215
#define IDC_OPEN                        1215
#define IDC_BUYMULTI                    1215
#define IDC_TAXSHAA                     1216
#define IDC_HIGH                        1216
#define IDC_SELLLIMIT                   1216
#define IDC_TAXSHAB                     1217
#define IDC_LOW                         1217
#define IDC_STARTAMOUNT                 1217
#define IDC_TAXSHAFUND                  1218
#define IDC_CLOSE                       1218
#define IDC_BUYLOGIC                    1218
#define IDC_VOLUME                      1219
#define IDC_STATICTITLE                 1219
#define IDC_AMOUNT                      1220
#define IDC_STATICWARNING               1220
#define IDC_STATICYIELD2                1221
#define IDC_SELLLOGIC                   1222
#define IDC_STOCKTECH                   1223
#define IDC_STOPLOSING                  1224
#define IDC_SELLMULTI                   1224
#define IDC_STOPPROFIT                  1225
#define IDC_KTYPELONG                   1226
#define IDC_KTYPEINDEX                  1227
#define IDC_SAVEAS                      1231
#define IDC_COLORCLASS                  1232
#define IDC_DJ                          1234
#define IDC_LINE6                       1235
#define IDC_STATICSTOCKTECH             1236
#define IDC_TABCTRL                     1237
#define IDC_OPRECORD                    1238
#define IDC_STOCKOWN                    1239
#define IDC_NEXTOP                      1240
#define IDC_BUYTIMES                    1242
#define IDC_VICTORYTIMES                1243
#define IDC_YIELDMAX                    1244
#define IDC_YIELDMIN                    1245
#define IDC_YIELDFIN                    1246
#define IDC_YIELDINDEX                  1247
#define IDC_YIELDSTDDEV                 1248
#define IDC_XIAPU                       1249
#define IDC_CURVE                       1250
#define IDC_SCROLLBAR                   1251
#define IDC_SCROLLBAR1                  1252
#define IDC_STATICEXPLAIN               1253
#define IDC_DELETEOP                    1254
#define IDC_SHARE                       1255
#define IDC_TIMEEXPLAIN                 1255
#define IDC_SHAREPRICE                  1256
#define IDC_RATECOST                    1257
#define IDC_TIME                        1258
#define IDC_OPERATE                     1259
#define IDC_STOCK                       1260
#define IDC_VALUE                       1261
#define IDC_STATICVALUE                 1262
#define IDC_LISTINFO                    1263
#define IDC_PRICE                       1263
#define IDC_STATICTIME                  1264
#define IDC_EDITMORETHAN                1265
#define IDC_EDITLESSTHAN                1266
#define IDC_LISTCOND                    1267
#define IDC_RADIOAND                    1268
#define IDC_RADIOOR                     1269
#define IDC_ALL                         1270
#define IDC_SHAA                        1271
#define IDC_STATICINFO                  1271
#define IDC_SHAB                        1272
#define IDC_GOLDENFORK                  1272
#define IDC_SZNA                        1273
#define IDC_DEADFORK                    1273
#define IDC_SZNB                        1274
#define IDC_LONG                        1274
#define IDC_SUPPORT                     1274
#define IDC_LISTRESULT                  1275
#define IDC_SHORT                       1275
#define IDC_RESISTANCE                  1275
#define IDC_BUY                         1276
#define IDC_SELL                        1277
#define IDC_EMADAYS1                    1278
#define IDC_EMADAYS2                    1279
#define IDC_DIFDAYS                     1280
#define IDC_DEVIATEONBOTTOM             1281
#define IDC_DEVIATEONTOP                1282
#define IDC_SOLD                        1285
#define IDC_BOUGHT                      1286
#define IDC_MADAYS                      1287
#define IDC_3K2D                        1288
#define IDC_QUOTIETY                    1288
#define IDC_3D2K                        1289
#define IDC_RSVDAYS                     1290
#define IDC_KDAYS                       1291
#define IDC_DDAYS                       1292
#define IDC_MAHLDAYS                    1293
#define IDC_CVDAYS                      1294
#define IDC_CHECKSTOPLOSING             1294
#define IDC_CHECKSTOPPROFIT             1295
#define IDC_CHECKLONG                   1296
#define IDC_CHECKINDEX                  1297
#define IDC_STATICPRICE                 1298
#define IDC_PREVIEW                     1299
#define IDC_FILE_DEST                   1300
#define IDC_FILE_EXPLORER               1301
#define IDC_PATH_SRCSH                  1302
#define IDC_FILE                        1302
#define IDC_TDXFILE_EXPLORER            1302
#define IDC_SRCSH_EXPLORER              1303
#define IDC_FILE_SRC                    1303
#define IDC_PATH_SRCSZ                  1304
#define IDC_FILE_TDX                    1304
#define IDC_SRCSZ_EXPLORER              1305
#define IDC_FILE_FXJ                    1305
#define IDC_SAVE                        1306
#define IDC_FXJFILE_EXPLORER            1306
#define IDC_SAVE2                       1307
#define IDC_PATH_FXJBLOCK               1307
#define IDC_FXJBLOCKPATH_EXPLORER       1308
#define IDC_RADIO_DIFFPERCENTMORE       1309
#define IDC_RADIO_DIFFPERCENTLESS       1310
#define IDC_RADIO_TRADEVOLUME           1311
#define IDC_DIFFPERCENTMORE             1312
#define IDC_RADIO_PERSONAL              1313
#define IDC_RADIO_ORGANIZATION          1314
#define IDC_RADIO_COMPANY               1315
#define IDC_COMBO_DISTRICT              1316
#define IDC_COMBO_STOCK                 1317
#define IDC_GOTO_INFO                   1318
#define IDC_STOCKGROUP                  1320
#define IDC_RUNSELECTOR                 1321
#define IDC_CHECK_REPORT                1322
#define IDC_FILE_F10                    1323
#define IDC_F10FILE_EXPLORER            1324
#define ID_VIEW_SLIST                   32783
#define ID_VIEW_REALTIME                32784
#define ID_VIEW_MULTISORT               32785
#define ID_VIEW_GRAPH                   32786
#define ID_VIEW_BASE                    32787
#define ID_MAINBAR_VIEW                 32788
#define ID_VIEW_ZOOMIN                  32793
#define ID_VIEW_ZOOMOUT                 32794
#define ID_OPTION_COLOR                 32800
#define ID_VIEW_RIGHT                   32801
#define ID_VIEW_LEFT                    32802
#define ID_DATA_MANAGE                  32815
#define ID_VIEW_RESUMEDRUP              32817
#define ID_VIEW_RESUMEDRDOWN            32818
#define ID_VIEW_NORESUMEDR              32819
#define ID_OPTION_SELF                  32821
#define ID_TOOL_CALCULATOR              32825
#define ID_VIEW_PDAY                    32826
#define ID_VIEW_PREV                    32827
#define ID_VIEW_NEXT                    32828
#define ID_SLIST_ALL                    32831
#define ID_SLIST_INDEX                  32836
#define ID_SLISTBAR_CLASS               32837
#define ID_SLIST_DOMAIN                 32838
#define ID_TOOL_NOTE                    32845
#define ID_DATA_EXPORT                  32846
#define ID_VIEW_PWEEK                   32849
#define ID_VIEW_PMONTH                  32850
#define ID_VIEW_PMIN5                   32851
#define ID_VIEW_PMIN15                  32852
#define ID_VIEW_PMIN30                  32853
#define ID_VIEW_PMIN60                  32854
#define ID_VIEW_WIZARD                  32855
#define ID_SLIST_EXPORTLIST             32857
#define ID_VIEW_FULLSCREEN              32865
#define ID_VIEW_SIMU                    32868
#define ID_VIEW_TECHOPTION              32870
#define ID_OPTION_SETGROUP              32871
#define ID_SIMU_RUN                     32880
#define ID_STRATEGY_SIMU                32881
#define ID_STRATEGY_STOCKS              32894
#define ID_HELP_PRODUCT                 32900
#define ID_DATA_DOWNLOAD                32901
#define IDS_SELECTORVIEW_CODE           32902
#define IDS_SELECTORVIEW_NAME           32903
#define IDS_SELECTORVIEW_DATE           32904
#define IDS_SELECTORVIEW_CLOSE          32905
#define IDS_SELECTORVIEW_SIGNAL         32906
#define IDS_SELECTORVIEW_DISCRIPT       32907
#define ID_SLISTBAR_NAME                32926
#define ID_STRATEGY_NEW                 32928
#define ID_STRATEGY_CLOSE               32929
#define ID_STRATEGY_SAVE                32930
#define ID_STRATEGY_SAVE_AS             32931
#define ID_STRATEGY_SAVEALL             32932
#define ID_DATA_DATASOURCE              32933
#define ID_HELP_REGISTER                32934
#define ID_HELP_DECLARE                 32935
#define ID_SLIST_STRATEGY               32936
#define ID_SLIST_SHAA                   32937
#define ID_SLIST_SHAB                   32938
#define ID_SLIST_SZNA                   32939
#define ID_SLIST_SZNB                   32940
#define ID_SLIST_SHABOND                32941
#define ID_SLIST_SZNBOND                32942
#define ID_SLIST_SETCOLUMN              32943
#define ID_SLIST_BASEINDEX              32944
#define ID_SYS_AUTOUPGRADE              32945
#define ID_SLISTBAR_DATE                32946
#define ID_SLIST_DOMAIN_START           32947
#define ID_SLIST_DOMAIN_END             33046
#define ID_SLIST_GROUP_START            33047
#define ID_SLIST_GROUP_END              33146
#define ID_OPTION_ADDTOGROUP_START      33147
#define ID_OPTION_ADDTOGROUP_END        33246
#define ID_SLIST_GROUP                  33249
#define ID_DATA_RECALCULATEYIELD        33251
#define ID_VIEW_PAGELEFT                33252
#define ID_VIEW_PAGERIGHT               33253
#define ID_VIEW_HOME                    33254
#define ID_VIEW_END                     33255
#define ID_OPTION_ADDTOGROUP            33259
#define ID_SLIST_GROUP1                 33260
#define ID_SLIST_DOMAIN1                33261
#define ID_VIEW_VIEWSZZS                33262
#define ID_VIEW_VIEWSZNZZ               33263
#define ID_VIEW_VIEWSZYBL               33264
#define ID_VIEW_VIEWSZAG                33265
#define ID_VIEW_VIEWSZBG                33266
#define ID_VIEW_VIEWSZNCZ               33267
#define ID_VIEW_VIEWSZNCFAZ             33268
#define ID_VIEW_VIEWSZNCFBZ             33269
#define ID_VIEW_MAINDATACLOSE           33272
#define ID_VIEW_MAINDATAOPEN            33273
#define ID_VIEW_MAINDATAAVERAGE         33274
#define ID_VIEW_TECHKLINE               33275
#define ID_VIEW_TECHTREND               33276
#define ID_VIEW_TECHENERGY              33277
#define ID_VIEW_TECHSWING               33278
#define ID_VIEW_TECHOTHER               33279
#define ID_VIEW_TECH_START              33280
#define ID_VIEW_TECH_END                34280
#define ID_INFO_STOCKSTAR               34281
#define ID_VIEW_INFO                    34282
#define ID_INFO_SOHU                    34285
#define ID_INFO_SINA                    34286
#define ID_INFO_163                     34287
#define ID_OPTION_PROXYSET              34288
#define ID_VIEW_REPORT                  34289
#define ID_STRATEGY_REPORT              34290
#define ID_MAINBAR_SETTING              34291
#define ID_MAINBAR_TECH                 34292
#define ID_MAINBAR_PERIOD               34293
#define ID_STRATEGY_PROPERTY            34294
#define ID_VIEW_INSERT                  34296
#define ID_STRATEGY_REALOP              34297
#define ID_STRATEGY_SETRATE             34298
#define ID_STRATEGY_SETRULE             34299
#define ID_SLISTBAR_DOMAIN              34300
#define ID_SLISTBAR_GROUP               34301
#define ID_WIZARDVIEW_LARGEICONS        34302
#define ID_WIZARDVIEW_SMALLICONS        34303
#define ID_WIZARDVIEW_LIST              34304
#define ID_WIZARDVIEW_DETAILS           34305
#define ID_OPTION_FONTSLIST             34308
#define ID_OPTION_FONTBASE              34309
#define ID_OPTION_ADDTOSTRATEGY_START   34310
#define ID_OPTION_ADDTOSTRATEGY_END     34509
#define ID_OPTION_ADDTOSTRATEGY         34512
#define ID_TOOL_FILTERINFO              34513
#define ID_VIEW_TECHCLK                 34514
#define ID_HELP_PURCHASE                34515
#define ID_VIEW_MAINBARTEXT             34516
#define ID_SYS_STARTTONGSHI             34518
#define ID_SYS_STOPTONGSHI              34519
#define ID_SLIST_GROUPSELF              34521
#define ID_REALTIME_MSSZAG              34525
#define ID_REALTIME_MSSZBG              34526
#define ID_REALTIME_MSSZZQ              34527
#define ID_REALTIME_MSSZNAG             34528
#define ID_REALTIME_MSSZNBG             34529
#define ID_REALTIME_MSSZNZQ             34530
#define ID_REALTIME_PREV                34531
#define ID_REALTIME_NEXT                34532
#define ID_REALTIME_LEFT                34533
#define ID_REALTIME_RIGHT               34534
#define ID_REALTIME_HOME                34535
#define ID_REALTIME_END                 34536
#define ID_REALTIME_VIEWSZZS            34537
#define ID_REALTIME_VIEWSZYBL           34538
#define ID_REALTIME_VIEWSZAG            34539
#define ID_REALTIME_VIEWSZBG            34540
#define ID_REALTIME_VIEWSZNCZ           34541
#define ID_REALTIME_VIEWSZNZZ           34542
#define ID_REALTIME_VIEWSZNCFAZ         34543
#define ID_REALTIME_VIEWSZNCFBZ         34544
#define ID_SLIST_SHAASORTDP             34545
#define ID_SLIST_SHABSORTDP             34546
#define ID_SLIST_SZNASORTDP             34547
#define ID_SLIST_SZNBSORTDP             34548
#define ID_SLIST_SHABONDSORTDP          34549
#define ID_SLIST_SZNBONDSORTDP          34550
#define ID_REALTIME_LBDK                34551
#define ID_REALTIME_MMLD                34552
#define ID_OPTION_SELECTTRADER          34554
#define ID_TOOL_TRADER                  34555
#define ID_SYS_SETUPTONGSHI             34556
#define ID_REALTIME_ONESTOCK            34557
#define ID_REALTIME_TWOSTOCK            34558
#define ID_REALTIME_FOURSTOCK           34559
#define ID_REALTIME_SIXSTOCK            34560
#define ID_REALTIME_NINESTOCK           34561
#define ID_REALTIME_REPORTDETAIL        34562
#define ID_REALTIME_PRICELINE           34563
#define ID_INFO_F10                     34564
#define ID_INFO_SELF                    34565
#define ID_INFO_SHSE                    34566
#define ID_INFO_SZSE                    34567
#define ID_INFO_HKEX                    34568
#define ID_INFO_LSE                     34569
#define ID_INFO_NYSE                    34570
#define ID_INFO_NASDAQ                  34571
#define ID_INFO_P5W                     34572
#define ID_INFO_SSNEWS                  34573
#define ID_INFO_CS                      34574
#define ID_HELP_SHOWHELP                34575
#define ID_VIEW_TECHUSER                34577
#define ID_REALTIME_MINUTEDETAIL        34578
#define ID_REALTIME_BIGTRADEDETAIL      34579
#define ID_VIEW_KLINECANDLE             34580
#define ID_VIEW_KLINEAMERICA            34581
#define ID_VIEW_KLINETOWER              34582
#define ID_VIEW_THISTECHPARAM           34583
#define ID_VIEW_HIDETHISTECH            34584
#define ID_SYS_CONNECTSERVER            34585
#define ID_SYS_DISCONNECTSERVER         34586
#define ID_SYS_AUTOSAVE                 34587
#define ID_VIEW_F10                     34588
#define ID_SYS_NOTIFYICON               34589
#define ID_TOOL_ALARM                   34590
#define ID_VIEW_SELECTOR                34591
#define IDS_OPENFILE                    45461
#define IDS_SAVEFILE                    45462
#define IDS_SAVEFILECOPY                45463
#define IDS_TITLE_MAINBAR               45464
#define IDS_TITLE_VIEWBAR               45465
#define IDS_TITLE_MENUBAR               45466
#define IDS_TITLE_PERIODBAR             45467
#define IDS_TITLE_SLISTBAR              45468
#define IDS_TITLE_SIMUBAR               45469
#define IDS_STATICDOC_FAILED            45470
#define IDS_TITLE_WIZARDVIEW            45471
#define IDS_TITLE_SLISTVIEW             45472
#define IDS_TITLE_GRAPHVIEW             45473
#define IDS_TITLE_BASEVIEW              45474
#define IDS_TITLE_SIMUVIEW              45475
#define IDS_TITLE_WORKSPBAR             45476
#define IDS_TITLE_STRATEGYVIEW          45477
#define IDS_AUTHORIZEDUSER_UNKNOWN      45478
#define IDS_REGCODE_UNPURCHASED         45479
#define IDS_DATECOMBOBOX_MORE           45480
#define IDS_DATECOMBOBOX_NOW            45481
#define IDS_STRATEGY_FAILED             45482
#define IDS_STRATEGY_NONAME             45483
#define IDS_STRATEGYVIEW_STRATEGY       45484
#define IDS_MAINFRAME_SHINDEXTIP        45485
#define IDS_MAINFRAME_SZINDEXTIP        45486
#define IDS_STRATEGYVIEW_STOCKS         45487
#define IDS_STRATEGYVIEW_ACTIVED        45488
#define IDS_STRATEGYVIEW_SIMU           45489
#define IDS_STRATEGYVIEW_REPORT         45491
#define IDS_STRATEGYVIEW_REALOP         45492
#define IDS_CLOSESTRATEGYDLG_TITLE      45493
#define IDS_CLOSESTRATEGYDLG_PATHNAME   45494
#define IDS_MAINFRAME_PROGRESS          45495
#define IDS_MAINFRAME_WAITING           45496
#define IDS_MAINFRAME_FINISHED          45497
#define IDS_SETCOLOR_SAVEASTITLE        45498
#define IDS_SETCOLOR_COLORCLASSEXIST    45499
#define IDS_SETCOLOR_CANNOTDELETESYS    45500
#define IDS_SETCOLOR_DELETECONFIRM      45501
#define IDS_TITLE_REALTIMEVIEW          45502
#define IDS_TITLE_MULTISORTVIEW         45503
#define IDS_CONFIRM_ERRORQIANLONGPATH   45504
#define IDS_TYDATADLG_ERRORTIME         45505
#define IDS_SERVERS_REFRESHING          45506
#define IDS_SERVERS_REFRESHED           45507
#define IDS_TYDATADLG_OVERWRITE         45508
#define IDP_OLE_INIT_FAILED             45509
#define IDP_FAILED_TO_CREATE            45510
#define IDS_LOGIN_FAILED                45511
#define IDS_REFRESHSERVERS_FAILED       45512
#define IDS_TYDATADLG_ERRORCREATEFILE   45513
#define IDS_NOSERVER_DEFINED            45514
#define IDS_DOWNLOAD_FINISHED           45515
#define IDS_DATA_DOWNLOADING            45516
#define IDS_DOWNLOAD_PAUSED             45517
#define IDS_REFRESHSERVERS_PAUSED       45518
#define IDS_DOWNLOAD_FAILED             45519
#define IDS_ROOTPATH_ERROR              45520
#define IDS_DLMSG_REPORT                45521
#define IDS_DLMSG_DAY                   45522
#define IDS_DLMSG_BASE                  45523
#define IDS_DLMSG_XDR                   45524
#define IDS_TYDATADLG_REPORTFMT         45525
#define IDS_DLMSG_MIN5                  45526
#define IDS_DLMSG_CONNECTING            45527
#define IDS_DLMIN5_NOTSUPPORT           45528
#define IDS_COMMA                       45529
#define IDS_FULLSTOP                    45530
#define IDS_SELECTPACKAGE_FIRST         45531
#define IDS_INSTALL_FINISHED            45532
#define IDS_INSTALL_PAUSED              45533
#define IDS_ERROR_QIANLONGPATH          45534
#define IDS_SUCCESS_QIANLONGPATH        45535
#define IDS_TESTOK_QIANLONGPATH         45536
#define IDS_SELECT_DIRECTORY            45537
#define IDS_EVALUATEFMT                 45538
#define IDS_EVALUATEINFO                45539
#define IDS_USERNAMETOOSHORTFMT         45540
#define IDS_REGCODETOOSHORT             45541
#define IDS_INVALIDREGCODE              45542
#define IDS_STRATEGYNAME                45543
#define IDS_STRATEGYPATH                45544
#define IDS_STRATEGYMODTIME             45545
#define IDS_STRATEGYOPENSTATUS          45546
#define IDS_STRATEGYOPENED              45547
#define IDS_SETPRPT_INVALIDPATH         45548
#define IDS_DLBASE_NOTSUPPORT           45549
#define IDS_MULTISORT_FALL              45550
#define IDS_MULTISORT_DIFF              45551
#define IDS_MULTISORT_RISEMIN5          45552
#define IDS_MULTISORT_FALLMIN5          45553
#define IDS_MULTISORT_VOLRATIO          45554
#define IDS_MULTISORT_BSRATIOASC        45555
#define IDS_MULTISORT_BSRATIODESC       45556
#define IDS_MULTISORT_AMOUNT            45557
#define IDS_MULTISORT_RISE              45558
#define IDS_SELECTTRADER_ERRFILE        45559
#define IDS_SETDRDATA_FILENOTEXISTS     45560
#define IDS_SETDRDATA_INSTALLOK         45561
#define IDS_SETDRDATA_INSTALLFAIL       45562
#define IDS_SETBASE_FILENOTEXISTS       45563
#define IDS_SETBASE_INSTALLF10OK        45564
#define IDS_SETBASE_INSTALLF10FAIL      45565
#define IDS_SETBASE_INSTALLTDXOK        45566
#define IDS_SETBASE_INSTALLTDXFAIL      45567
#define IDS_ALARMRESULT_REASON          45568
#define IDS_ALARMSETTING_NOTNUMBER      45569
#define IDS_ALARMSETTING_NOCONDSELECTED 45570
#define IDS_REGAPPLYEVA_NOUSERNAME      45571
#define IDS_REGAPPLYEVA_NOCOUNTRY       45572
#define IDS_REGAPPLYEVA_NOEMAIL         45573
#define IDS_REGAPPLYEVA_APPLYOK         45574
#define IDS_REGAPPLYEVA_APPLYFAIL       45575
#define IDS_SETBASE_INSTALLFXJOK        45576
#define IDS_SETBASE_INSTALLFXJFAIL      45577
#define IDS_SETBASE_INSTALLFXJBLOCKOK   45578
#define IDS_SETBASE_INSTALLFXJBLOCKFAIL 45579
#define IDS_SLHHDR_DAY                  45633
#define IDS_SLISTVIEW_CLASS             45634
#define IDS_SLISTVIEW_A                 45635
#define IDS_SLISTVIEW_SZNB              45636
#define IDS_SLISTVIEW_SHB               45637
#define IDS_SLISTVIEW_BOND              45638
#define IDS_SLISTVIEW_FUND              45639
#define IDS_SLISTVIEW_SELF              45640
#define IDS_SLISTVIEW_GROUP             45641
#define IDS_SLISTVIEW_DOMAIN            45642
#define IDS_SETCOLUMN_NAME              45651
#define IDS_SETCOLUMN_DESCRIPT          45652
#define IDS_SETCOLUMN_NOSEL             45653
#define IDS_SETCOLUMN_FIRST             45654
#define IDS_SETCOLUMN_LAST              45655
#define IDS_SETCOLUMN_NOTUSERDEFINE     45656
#define IDS_SETCOLUMN_QUERYDEL          45657
#define IDS_SETCOLUMN_USERDEFINE        45658
#define IDS_BASEINDEX_NAMEDEFAULT       45659
#define IDS_BASEINDEX_EXPRESSEXAMPLE    45660
#define IDS_BASEINDEX_NONAME            45661
#define IDS_SETCOLUMN_SETDEFAULT        45662
#define IDS_BASEVIEW_NOBASEDATA         45663
#define IDS_SLISTVIEW_UP                45664
#define IDS_SLISTVIEW_DOWN              45665
#define IDS_UPGRADE_PAUSED              45670
#define IDS_UPGRADE_NOTFOUND            45671
#define IDS_UPGRADE_DLOK                45672
#define IDS_UPGRADE_CANNOTOPENFILE      45673
#define IDS_EXPRESS_ERRPARSERSTACK      45674
#define IDS_BASEINDEX_NAMETOOLONG       45683
#define IDS_HELPTIP_SLIST               45684
#define IDS_EXPORTDB_NODEST             45685
#define IDS_EXPORTDB_NOTXTDEST          45686
#define IDS_EXPORTDB_NOMDBDEST          45687
#define IDS_EXPORTDB_NOCSVDEST          45688
#define IDS_EXPORTDB_FINISHED           45689
#define IDS_SECRET_ASSERTMESSAGE        45690
#define IDS_SECRET_FUNCLIMIT            45691
#define IDS_REGISTER_SUCCESS            45692
#define IDS_REGISTER_PURCHASED          45693
#define IDS_REGISTER_NOTIMELIMIT        45694
#define IDS_SLISTBAR_NODOMAIN           45695
#define IDS_REGISTER_LEFTDAYSTITLE      45696
#define IDS_SETCOLUMN_SETTING           45703
#define IDS_RECALYIELD_NOSZZS           45704
#define IDS_EXPORTDB_ERRTXTDEST         45705
#define IDS_EXPORTDB_ERRMDBDEST         45706
#define IDS_EXPORTDB_ERRCSVDEST         45707
#define IDS_EXPORTDB_ERRODBCDEST        45708
#define IDS_EXPORTDB_NOODBCDEST         45709
#define IDS_LISTEXPORT_TABLENAME        45710
#define IDS_SLISTBAR_NOGROUP            45711
#define IDS_DOMAIN_SELF                 45712
#define IDS_DOMAIN_ALL                  45714
#define IDS_DOMAIN_INDEX                45715
#define IDS_DOMAIN_CLASSSHAA            45716
#define IDS_DOMAIN_CLASSSHAB            45717
#define IDS_DOMAIN_CLASSSZNA            45718
#define IDS_DOMAIN_CLASSSZNB            45719
#define IDS_DOMAIN_CLASSSHABOND         45720
#define IDS_DOMAIN_CLASSSZNBOND         45721
#define IDS_SETGROUP_GROUPALREADYEXIST  45722
#define IDS_SETGROUP_ADDFAILED          45723
#define IDS_SETGROUP_ADDSUCCESS         45724
#define IDS_SETGROUP_DELETEFAILED       45725
#define IDS_SETGROUP_DELETESUCCESS      45726
#define IDS_SETGROUP_NOSELECTEDGROUP    45727
#define IDS_DOMAIN_MOREDOMAIN           45728
#define IDS_SETGROUP_USERCANCEL         45729
#define IDS_DOMAIN_MOREGROUP            45730
#define IDS_SETCOLUMN_NOSELECT          45731
#define IDS_SETGROUP_DELETECONFIRM      45732
#define IDS_SETGROUP_INPUTGNAME         45733
#define IDS_EXPORT_SELECTSTK            45735
#define IDS_EXPORT_DEST                 45736
#define IDS_EXPORT_START                45738
#define IDS_FINISHBUTTON                45739
#define IDS_CLOSEBUTTON                 45740
#define IDS_SELECTSTK_NOSELECTED        45741
#define IDS_EXPORT_OPTION               45743
#define IDS_EXPORTDEST_DATE             45747
#define IDS_EXPORTDEST_OPEN             45748
#define IDS_EXPORTDEST_HIGH             45749
#define IDS_EXPORTDEST_LOW              45750
#define IDS_EXPORTDEST_CLOSE            45751
#define IDS_EXPORTDEST_AMOUNT           45752
#define IDS_EXPORTDEST_VOLUME           45753
#define IDS_EXPORTDEST_CONFIRMCLOSE     45763
#define IDS_SETDRDATA_DATE              45764
#define IDS_SETDRDATA_BONUS             45765
#define IDS_SETDRDATA_BONUSSHARE        45766
#define IDS_SETDRDATA_RATIONSHARE       45767
#define IDS_SETDRDATA_RATIONVALUE       45768
#define IDS_SETDRDATA_NOSTOCK           45769
#define IDS_SETCOLUMN_SAMEASYIELDAVERAGE 45770
#define IDS_SETCOLUMN_IFRECALCULATE     45771
#define IDS_INSTALLPAC_IFRECALCULATE    45772
#define IDS_STOCKGRAPH_KLINE            45773
#define IDS_STOCKGRAPH_FONTNAME         45774
#define IDS_STOCKGRAPH_TIME             45775
#define IDS_STOCKGRAPH_OPEN             45776
#define IDS_STOCKGRAPH_HIGH             45777
#define IDS_STOCKGRAPH_LOW              45778
#define IDS_STOCKGRAPH_CLOSE            45779
#define IDS_STOCKGRAPH_VOLUME           45780
#define IDS_STOCKGRAPH_AMOUNT           45781
#define IDS_STOCKGRAPH_YIELDAVERAGE     45782
#define IDS_STOCKGRAPH_DAY              45783
#define IDS_STOCKGRAPH_YIELDSTDDEV      45784
#define IDS_STOCKGRAPH_BEITE            45785
#define IDS_STOCKGRAPH_XIAPU            45786
#define IDS_STOCKGRAPH_CHANGEHAND       45787
#define IDS_STOCKGRAPH_RATIOVOLUME      45788
#define IDS_STOCKGRAPH_SHARECURRENCY    45789
#define IDS_STOCKGRAPH_NETASSETPS       45790
#define IDS_STOCKGRAPH_EPS              45791
#define IDS_STOCKGRAPH_RS               45792
#define IDS_STOCKGRAPH_TIME2            45793
#define IDS_STOCKGRAPH_PRICEAVERAGE     45794
#define IDS_STOCKGRAPH_RELATIVECHANGEHAND 45795
#define IDS_GRAPHTAB_PARAM              45796
#define IDS_GRAPHTAB_COST               45797
#define IDS_STOCKGRAPH_SHARETOTAL       45798
#define IDS_TITLE_INFOVIEW              45799
#define IDS_SETPARAM_INVALID            45800
#define IDS_TITLE_GROUPVIEW             45801
#define IDS_TITLE_TECHSVIEW             45802
#define IDS_GROUPVIEW_GROUP             45803
#define IDS_GROUPVIEW_DOMAIN            45804
#define IDS_STRATEGY_SETPRPT            45805
#define IDS_PROPERTYSHEET_NEXT          45806
#define IDS_STOCKGRAPH_NOKDATA          45807
#define IDS_STOCKGRAPH_PROJECT          45808
#define IDS_STOCKGRAPH_PRIMARY          45809
#define IDS_STOCKGRAPH_MEDIATE          45810
#define IDS_STOCKGRAPH_MIGHT            45811
#define IDS_STOCKGRAPH_PRESSURE         45812
#define IDS_STOCKGRAPH_UPHOLD           45813
#define IDS_DOWNLOAD_UPGRADENOW         45814
#define IDS_STRATEGY_SELECTSTK          45815
#define IDS_STRATEGY_INVALIDFILE        45816
#define IDS_SETPRPT_INVALIDTITLE        45816
#define IDS_GRAPHTAB_FLAME              45817
#define IDS_EDITKDATA_NOTNUMBER         45818
#define IDS_STRATEGYVIEW_PROPERTY       45819
#define IDS_SIMUVIEW_SIMU               45820
#define IDS_SIMUVIEW_START              45821
#define IDS_SIMUVIEW_PAUSE              45822
#define IDS_SIMUVIEW_CONTINUE           45823
#define IDS_SIMUVIEW_MSGNOSTRATEGY      45824
#define IDS_STRATEGYVIEW_RATE           45825
#define IDS_STRATEGYVIEW_RULE           45826
#define IDS_SETRATE_NOTNUMBER           45827
#define IDS_GRAPHTAB_ACTIVITY           45828
#define IDS_STOCKGRAPH_RECENTCWDISFMT   45829
#define IDS_STOCKGRAPH_PASTCWDISFMT     45830
#define IDS_STOCKGRAPH_GAINPERCENT      45831
#define IDS_STOCKGRAPH_COSTAVE          45832
#define IDS_STOCKGRAPH_MASSFMT90        45833
#define IDS_STOCKGRAPH_MASSFMT70        45834
#define IDS_SETBASEDATA_NOSTOCK         45835
#define IDS_SETBASEDATA_NOTNUMBER       45836
#define IDS_SETBASEDATA_SHARENOTMATCH   45837
#define IDS_SIMUVIEW_INVALIDDATA        45838
#define IDS_SIMUVIEW_RUNCANNOTCLOSE     45839
#define IDS_STRATEGY_SETRATE            45840
#define IDS_STRATEGY_SETRULE            45841
#define IDS_STOCKGRAPH_PE               45842
#define IDS_SETKDATA_NOTNUMBER          45843
#define IDS_TITLE_SELECTORVIEW          45844
#define IDS_SIMULATION_LOGICAND         45848
#define IDS_SIMULATION_LOGICOR          45849
#define IDS_SETRULE_NOSELECTED          45850
#define IDS_SIMUVIEW_TIMEINVALID        45851
#define IDS_SIMULATION_DOWNLOADNOW      45852
#define IDS_SIMUREPORT_OPRECORD         45855
#define IDS_SIMUREPORT_CURVE            45856
#define IDS_SIMUREPORT_STOCKOWN         45857
#define IDS_SIMUREPORT_TIME             45858
#define IDS_SIMUREPORT_OP               45859
#define IDS_SIMUREPORT_STOCK            45860
#define IDS_SIMUREPORT_SHARE            45861
#define IDS_SIMUREPORT_SHAREPRICE       45862
#define IDS_SIMUREPORT_RATECOST         45863
#define IDS_SIMUREPORT_BUY              45864
#define IDS_SIMUREPORT_SELL             45865
#define IDS_SIMUREPORT_OWNSHARE         45866
#define IDS_SIMUREPORT_CASH             45867
#define IDS_SIMUREPORT_ASSET            45868
#define IDS_SIMUREPORT_AMOUT            45869
#define IDS_SIMUREPORT_YIELDLINE        45870
#define IDS_SIMUREPORT_STORELINE        45871
#define IDS_SIMUREALOP_NEXTOP           45872
#define IDS_SIMUREALOP_SHARE            45873
#define IDS_SIMUREALOP_SHAREPRICE       45874
#define IDS_SIMUREALOP_STOCKOWN         45875
#define IDS_SIMUREALOP_RESETCONFIRM     45876
#define IDS_SIMUREALOP_OPRECORDNOSEL    45877
#define IDS_SIMUREALOP_CANNOTDELETE     45878
#define IDS_SIMUADDOP_NOSTOCK           45879
#define IDS_SIMUADDOP_NOTNUMBER         45880
#define IDS_SIMUADDOP_LOGICERROR        45881
#define IDS_SIMUREALOP_DELETELATER      45882
#define IDS_SIMUADDOP_ADDWILLDELETE     45883
#define IDS_SIMUVIEW_REALHASNEXTOP      45888
#define IDS_SIMUREPORT_AMOUNT           45889
#define IDS_SIMUREALOP_ADDSTOCKFAILED   45890
#define IDS_SIMUREALOP_MODIFIEDCASHFAILED 45891
#define IDS_SIMUADDSTOCK_CASH           45892
#define IDS_SIMUADDSTOCK_MODCASH        45893
#define IDS_FILTERINFO_ME               45896
#define IDS_FILTERINFO_AND              45897
#define IDS_FILTERINFO_LE               45898
#define IDS_FILTERINFO_NOSELECTEDCOND   45899
#define IDS_FILTERINFO_NOSELECTEDINFO   45900
#define IDS_FILTERINFO_INVALIDCOND      45901
#define IDS_FILTERINFO_NOCOND           45902
#define IDS_SIMUREALOP_EVACANNOTVIEWNEXTOP 45903
#define IDS_SIMUREALOP_EXPLAINNEXTOP    45904
#define IDS_SIMUREALOP_EXPLAINOPRECORD  45905
#define IDS_SIMUREALOP_TIMEEXPLAINFMT   45906
#define IDS_SIMUREPORT_BUYPRICE         45907
#define IDS_SIMUREPORT_NOWPRICE         45908
#define IDS_STRATEGY_SETRULELONG        45909
#define IDS_STRATEGY_SETRULEINDEX       45910
#define IDS_SIMUADVANCED_NOTNUMBER      45911
#define IDS_SIMUADVANCED_NOSELECTEDLONG 45912
#define IDS_SIMUADVANCED_NOSELECTEDINDEX 45913
#define IDS_REALTIME_TITLE              45914
#define IDS_REALTIME_BSRATIO            45915
#define IDS_REALTIME_BSDIFF             45916
#define IDS_REALTIME_SELL5              45917
#define IDS_REALTIME_SELL4              45918
#define IDS_REALTIME_SELL3              45919
#define IDS_REALTIME_SELL2              45920
#define IDS_REALTIME_SELL1              45921
#define IDS_REALTIME_BUY1               45922
#define IDS_REALTIME_BUY2               45923
#define IDS_REALTIME_BUY3               45924
#define IDS_REALTIME_BUY4               45925
#define IDS_REALTIME_BUY5               45926
#define IDS_REALTIME_PRICENOW           45927
#define IDS_REALTIME_PRICEAVE           45928
#define IDS_REALTIME_PRICEDIFF          45929
#define IDS_REALTIME_PRICEOPEN          45930
#define IDS_REALTIME_PRICEDIFFPERCENT   45931
#define IDS_REALTIME_PRICEHIGH          45932
#define IDS_REALTIME_VOLSUM             45933
#define IDS_REALTIME_PRICELOW           45934
#define IDS_REALTIME_VOLNOW             45935
#define IDS_REALTIME_VOLRATION          45936
#define IDS_REALTIME_VOLOUTER           45937
#define IDS_REALTIME_VOLINNER           45938
#define IDS_REALTIME_TIME               45939
#define IDS_REALTIME_PRICE              45940
#define IDS_REALTIME_VOLUME             45941
#define IDS_REALTIME_AMOUNT             45942
#define IDS_REALTIME_ADVANCE            45943
#define IDS_REALTIME_DECLINE            45944
#define IDS_REALTIME_LBDK               45945
#define IDS_REALTIME_MMLD               45946
#define IDS_REALTIME_REPORTDETAILTITLE  45947
#define IDS_REALTIME_MINUTEDETAILTITLE  45948
#define IDS_REALTIME_BIGTRADEDETAILTITLE 45949
#define IDS_REALTIME_STOCKNAME          45950
#define IDS_REALTIMETAB_QUOTE           45951
#define IDS_REALTIMETAB_PRICE           45952
#define IDS_REALTIMETAB_MINUTE          45953
#define IDS_REALTIMETAB_BUYSELLEX       45954
#define IDS_REALTIMETAB_VALUE           45955
#define IDS_REALTIMETAB_DISTRIBUTE      45956
#define IDS_REALTIMETAB_BIGTRADE        45957
#define IDS_REALTIME_RISINGLIMIT        45958
#define IDS_REALTIME_FALLINGLIMIT       45959
#define IDS_REALTIME_AH                 45960
#define IDS_REALTIME_NH                 45961
#define IDS_REALTIME_NL                 45962
#define IDS_REALTIME_AL                 45963
#define IDS_REALTIME_SELL8              45964
#define IDS_REALTIME_SELL7              45965
#define IDS_REALTIME_SELL6              45966
#define IDS_REALTIME_BUY6               45967
#define IDS_REALTIME_BUY7               45968
#define IDS_REALTIME_BUY8               45969
#define IDW_MENUBAR                     0xE8F0
#define IDW_MAINBAR                     0xE8F1
#define IDW_VIEWBAR                     0xE8F2
#define IDW_PERIODBAR                   0xE8F3
#define IDW_SLISTBAR                    0xE8F4
#define IDW_SIMUBAR                     0xE8F5
#define IDW_PROGRESSBAR                 0xE8F6
#define IDW_WORKSPBAR                   0xE8F7
#define IDW_SLISTTABBAR                 0xE8F8

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        293
#define _APS_NEXT_COMMAND_VALUE         34592
#define _APS_NEXT_CONTROL_VALUE         1325
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
